# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='files',
            field=models.FileField(null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='document',
            name='filelist',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
