# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20161105_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='files',
        ),
    ]
