# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_remove_document_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='hits',
        ),
        migrations.AlterField(
            model_name='document',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
