# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticec',
            new_name='Notice',
        ),
    ]
