# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20161126_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeboard',
            name='f_comment_num',
            field=models.IntegerField(null=True),
        ),
    ]
