# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
