# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20161125_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comment_num',
            field=models.IntegerField(null=True),
        ),
    ]
