# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoBoard',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateField(blank=True)),
                ('hits', models.IntegerField(blank=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
