# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_submit',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
