# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20161013_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='right_problems',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_submit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
