# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='level',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
