# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('problem', '0002_problem_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.UserProfile'),
        ),
    ]
