# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_remove_problem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='artifact',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
