# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_problem_artifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='corrects',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='submits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
