# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_answerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='importance',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
