# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0009_auto_20161012_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='downfile',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
