# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0010_problem_downfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlog',
            name='problem_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='answerlog',
            name='problem_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
