# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0011_auto_20161013_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlog',
            name='submit_answer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='right_answer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
